# Generated by Django 4.0.4 on 2022-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_is_deleted_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active_token',
            field=models.CharField(blank=True, default='153840', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='MP3150978246', max_length=12),
        ),
    ]
