# Generated by Django 4.0.4 on 2022-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_active_token_users_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='active_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='MP9824507136', max_length=12),
        ),
    ]
