# Generated by Django 4.0.4 on 2022-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_active_token_remove_users_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active_token',
            field=models.CharField(blank=True, default='703691', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='MP9186520347', max_length=12),
        ),
    ]
