# Generated by Django 4.0.4 on 2022-04-25 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_active_token_users_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_token',
            field=models.CharField(blank=True, default='379180', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='MP4381650972', max_length=12),
        ),
    ]
