# Generated by Django 4.0.4 on 2022-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_active_token_alter_users_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_token',
            field=models.CharField(blank=True, default='150237', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='MP3617802594', max_length=12),
        ),
    ]
