# Generated by Django 4.0.4 on 2022-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_active_token_alter_users_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_token',
            field=models.CharField(blank=True, default='790361', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='MP8714920653', max_length=12),
        ),
    ]
